### PR TITLE
make it a monorepo

### PR DESCRIPTION
**Pull request by jgravois**
take 2.

this 🐳 of a PR just shuffles the existing code around to use the same Lerna monorepo structure and tooling we use in `rest-js` and `hub.js` to automate CI, doc updates and publishing tags to GitHub and npm.

- [X] prep for rename to `Solution.js`
- [X] get acetate doc site up and running
- [X] all tests are _still_ passing.

it'd probably be a lot easier to sit down together and review this instead of poring over the diff.

cc/ @dbouwman

### CODE REVIEW

**Comment by jgravois** [comment]
just pushed up one more commit to:
1. rename the repo from Solutions.js > Solution.js
2. stub out `@esri/solution-viewer` and `@esri/solution-creator` packages
3. ensure acetate launches http://localhost:3000/solution.js/index.html

**Comment by jgravois** [comment]
thanks @jmhauck!

to do:
- [X] refactor demos (done by @MikeTschudi in #23)
- [ ] rename repo on GitHub (needs to be done by repo admin)
- [ ] ??

i'm also _more_ than happy to rebase this branch to clean up the history.

**Comment by jgravois** [comment]
i've rebased the branch.

this PR is a monster, so i'd feel better if y'all clicked the little 💚 button whenever you're ready.

if you **ever** need help with all the tooling or doc that we're introducing here, just say the word.

**Comment by MikeTschudi** [comment]
Merged into #23 and looks good

**Comment by jgravois** [comment]
is anything keeping this work from being merged into `develop`?

**Comment by MikeTschudi** [comment]
Fear of big PRs.   ;-)

**Pull request merged**
