### PR TITLE
Changes to support using adlib for swizzling

### PR DESCRIPTION
**Pull request by MikeTschudi**

### CODE REVIEW

**Comment by MikeTschudi** [comment]
Closing PR for now since the changes depend on an [arcgis-rest-js fix](https://github.com/Esri/arcgis-rest-js/commit/8173aa5c2d92b2f3f47ff108a8fb575fe449b99b)

**Comment by jgravois** [comment]
I can release `rest-js` today if it'd be helpful.

**Comment by MikeTschudi** [comment]
Yes, please!

**Comment by jgravois** [comment]
released as [`v1.16.1`](https://github.com/Esri/arcgis-rest-js/releases/tag/v1.16.1) 🏄‍♀️

**Comment by MikeTschudi** [comment]
Thanks, @jgravois--"All checks have passed"!

**Pull request merged**
